# Generated by Django 5.1.5 on 2026-01-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
